version: "3.1"

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: my_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
